USE crop_disease_db;

INSERT INTO diseases (disease_name, symptoms, causes, prevention, treatment, crop_type) VALUES
('Pepper__bell___Bacterial_spot', 
 'Small, yellow-green spots on leaves that turn brown and water-soaked. Lesions may expand and merge, causing leaves to drop.', 
 'Xanthomonas campestris pv. vesicatoria bacterium, spread by rain splash, overhead watering, and contaminated seeds.', 
 'Use certified pathogen-free seeds, practice crop rotation, keep foliage dry, and sanitize garden tools regularly.', 
 'Copper-based fungicides can help manage the spread of the disease when applied early and combined with pruning.', 
 'Pepper Bell'),

('Pepper__bell___healthy', 
 'Leaves are vibrant green, free of spots, blemishes, or wilting. Plant displays normal growth and healthy fruit development.', 
 'N/A - Plant is in healthy state with proper nutrients, water, and environment.', 
 'Maintain regular watering, appropriate sunlight, proper spacing, and routine monitoring for pests.', 
 'None required. Continue standard cultural practices.', 
 'Pepper Bell'),

('Potato___Early_blight', 
 'Small, dark brown to black spots with concentric rings ("target-board" effect) on older, lower leaves first.', 
 'Alternaria solani fungus, which overwinter in plant debris and soil, favored by warm, humid weather and wet leaves.', 
 'Rotate crops, clean field debris after harvest, plant resistant potato varieties, and apply mulch to reduce soil splash.', 
 'Apply protective fungicides like chlorothalonil, mancozeb, or copper-based sprays upon first sign of symptoms.', 
 'Potato'),

('Potato___Late_blight', 
 'Large, irregular water-soaked spots on leaves that turn dark brown to black. White velvety mold appears on leaf undersides in wet conditions.', 
 'Phytophthora infestans oomycete, a highly destructive pathogen that thrives in cool, wet, and humid conditions.', 
 'Plant certified healthy seed tubers, eliminate volunteer potatoes, and avoid overhead irrigation.', 
 'Immediately apply systemic or protective fungicides (e.g., metalaxyl, chlorothalonil, copper). Destroy infected crops to prevent epidemic.', 
 'Potato'),

('Potato___healthy', 
 'Foliage is green and bushy without spots, yellowing, or decay. Tubers are firm and clean.', 
 'N/A - Plant is in healthy state.', 
 'Maintain healthy soil, crop rotation, and correct moisture levels. Check for early signs of pests.', 
 'None required. Continue standard watering and weeding.', 
 'Potato'),

('Tomato_Bacterial_spot', 
 'Small, dark, water-soaked spots on leaves, stems, and fruit. Leaves may turn yellow and drop prematurely, exposing fruit to sunscald.', 
 'Xanthomonas bacterium species (X. vesicatoria, X. perforans, etc.), spread by splashing rain, dew, or contaminated tools.', 
 'Use disease-free seeds and transplants, avoid overhead watering, rotate crops, and do not work in wet fields.', 
 'Apply copper-based fungicides mixed with mancozeb to reduce bacterial spread on healthy leaves.', 
 'Tomato'),

('Tomato_Early_blight', 
 'Dark, concentric rings forming circular spots on older leaves. Leaves yellow around spots and eventually drop.', 
 'Alternaria solani fungus, which thrives in warm temperatures and high humidity/wetness.', 
 'Mulch soil, prune lower leaves, ensure wide plant spacing for airflow, and clean up crop residues at season end.', 
 'Use fungicides containing chlorothalonil, mancozeb, or copper fungicides at regular intervals when conditions favor disease.', 
 'Tomato'),

('Tomato_Late_blight', 
 'Dark, water-soaked patches on leaves and stems that rapidly turn black. White fuzzy growth appears on the undersides of leaves in humid weather.', 
 'Phytophthora infestans oomycete, which can kill tomato plants within days under wet, cool conditions.', 
 'Plant resistant varieties, destroy volunteer tomatoes, and ensure excellent air circulation.', 
 'Apply preventative copper-based or systemic fungicides. Promptly pull and dispose of infected plants (do not compost).', 
 'Tomato'),

('Tomato_Leaf_Mold', 
 'Pale green or yellow spots on upper leaf surfaces, corresponding to olive-green to purple velvety mold on leaf undersides.', 
 'Passalora fulva (formerly Cladosporium fulvum) fungus, very common in high humidity and greenhouse environments.', 
 'Improve ventilation in greenhouses, reduce humidity, prune lower leaves, and water at the base of plants.', 
 'Apply copper fungicides or sulfur-based sprays to manage outbreaks in high-risk environments.', 
 'Tomato'),

('Tomato_Septoria_leaf_spot', 
 'Numerous small, circular spots (1/16 to 1/8 inch) with dark borders and grey/tan centers. Tiny black specks (pycnidia) appear in centers.', 
 'Septoria lycopersici fungus, which is splash-dispersed from soil or infected plant debris.', 
 'Prune lower leaves to prevent contact with soil, apply mulch, avoid overhead watering, and weed regularly.', 
 'Spray fungicides containing chlorothalonil or copper-based compounds at the first sign of leaf spots.', 
 'Tomato'),

('Tomato_Spider_mites_Two_spotted_spider_mite', 
 'Yellow stippling or tiny specks on leaves, fine webbing on leaf undersides and stems. Leaves turn bronze, dry out, and drop.', 
 'Tetranychus urticae spider mites, tiny arachnids that thrive in hot, dry, and dusty conditions.', 
 'Spray plants with water to disrupt webs and wash off mites, encourage natural predators like ladybugs, and keep plants watered.', 
 'Apply insecticidal soaps, horticultural oils, neem oil, or specific miticides if populations are high.', 
 'Tomato'),

('Tomato__Target_Spot', 
 'Small, dark brown spots on leaves with faint concentric rings. Lesions can also form on stems and fruit, causing rot.', 
 'Corynespora cassiicola fungus, favored by warm, wet weather and prolonged leaf wetness.', 
 'Practice crop rotation, space plants well, and avoid overhead watering to reduce canopy moisture.', 
 'Apply azoxystrobin, chlorothalonil, or copper-based fungicides to protect healthy foliage.', 
 'Tomato'),

('Tomato__Tomato_YellowLeaf__Curl_Virus', 
 'Leaves curl upward and inward, turn yellow along margins, and show severe puckering. Plant growth is severely stunted.', 
 'Begomovirus transmitted by silverleaf whiteflies (Bemisia tabaci). Not spread by contact or seeds.', 
 'Use whitefly-resistant netting in greenhouses, set up yellow sticky traps, and control whitefly hosts.', 
 'No cure for the virus. Immediately remove and destroy infected plants. Use insecticidal soaps or systemic insecticides to control whiteflies.', 
 'Tomato'),

('Tomato__Tomato_mosaic_virus', 
 'Mottling of leaves with light and dark green patches (mosaic pattern), leaf crinkling, leaf narrowing, and stunted growth.', 
 'Tomato mosaic virus (ToMV), highly stable and easily transmitted mechanically by hands, tools, and clothing.', 
 'Disinfect tools with bleach or trisodium phosphate, wash hands with soap, plant certified seeds, and use resistant varieties.', 
 'No chemical treatment. Pull and burn infected plants. Sanitize the area and avoid planting solanaceous crops there next season.', 
 'Tomato'),

('Tomato_healthy', 
 'Foliage is healthy green, leaves are firm, and stems are strong. Free of spots, molds, wilting, or unusual discoloration.', 
 'N/A - Plant is healthy and growing under optimal environmental conditions.', 
 'Maintain healthy soil nutrients, appropriate watering schedules, weed control, and general observation.', 
 'None required. Continue standard plant care.', 
 'Tomato')
ON DUPLICATE KEY UPDATE 
 symptoms = VALUES(symptoms),
 causes = VALUES(causes),
 prevention = VALUES(prevention),
 treatment = VALUES(treatment),
 crop_type = VALUES(crop_type);
